name       : virtualenvwrapper
version    : 4.7.1
release    : 5
source     :
    - https://pypi.python.org/packages/source/v/virtualenvwrapper/virtualenvwrapper-4.7.1.tar.gz : 3bf73ede42a689adeedc8ac85662cb539665d3d029459bc8d3e6835ecd81ffde
license    : HPND
component  : programming.tools
summary    : Extensions to Ian Bicking's virtualenv tool
description: |
    virtualenvwrapper is a set of extensions to Ian Bicking's virtualenv
    tool.  The extensions include wrappers for creating and deleting virtual
    environments and otherwise managing your development workflow, making it
    easier to work on more than one project at a time without introducing
    conflicts in their dependencies.
builddeps  :
    - pkgconfig(python3)
    - python-setuptools
    - pbr
rundeps    :
    - python-stevedore
    - virtualenv
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
